# Generated by Django 4.2.9 on 2025-07-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_mealorder_mealorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="temp_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="temp_meal_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
