# Generated by Django 4.2.9 on 2025-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_chatsession_temp_data_chatsession_temp_meal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealorder",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
