# Generated by Django 4.2.9 on 2025-05-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_author_department_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rack_position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="row_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.department",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
