# Generated by Django 4.2.9 on 2025-07-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_mealorder_payment_reference_mealorder_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealorder",
            name="payment_reference",
        ),
    ]
