# Generated by Django 4.2.9 on 2025-05-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_book_rack_position_book_row_number_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("Available", "Available"), ("Rendered", "Rendered")],
                default="Available",
                max_length=20,
            ),
        ),
    ]
