# Generated by Django 4.2.9 on 2025-05-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_book_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="render_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="render_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="rendered_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="Sample", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="reg_number",
            field=models.CharField(default="Sample", max_length=20, unique=True),
        ),
    ]
