# Generated by Django 4.2.9 on 2025-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_mealorder_transaction_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealorder",
            name="phone_number_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
