# Generated by Django 4.2.9 on 2025-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_book_render_from_book_render_to_book_rendered_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="reg_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
