# Generated by Django 4.2.9 on 2025-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_mealorder_phone_number_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="temp_order_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
