# Generated by Django 4.2.9 on 2025-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_penalty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penalty",
            name="reason",
        ),
        migrations.AddField(
            model_name="penalty",
            name="days_late",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="penalty",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
