# Generated by Django 4.2.9 on 2025-07-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_chatsession_temp_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subitems",
                to="pages.menuitem",
            ),
        ),
    ]
