# Generated by Django 4.2.9 on 2025-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_remove_penalty_reason_penalty_days_late_penalty_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
