# Generated by Django 4.2.9 on 2025-05-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_penalty_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="penalty",
            old_name="issued_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="paid",
        ),
        migrations.AddField(
            model_name="penalty",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="days_late",
            field=models.IntegerField(),
        ),
    ]
