# Generated by Django 4.2.9 on 2025-07-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_year_student_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.department",
            ),
        ),
    ]
