# Generated by Django 4.2.9 on 2025-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_rename_issued_at_penalty_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("state", models.CharField(max_length=50)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
