# Generated by Django 4.2.9 on 2025-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_chatsession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="registration_number",
            new_name="reg_number",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="state",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="stage",
            field=models.CharField(default="initial", max_length=50),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
