# Generated by Django 4.2.9 on 2025-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_student_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="first_year_only",
            field=models.BooleanField(default=False),
        ),
    ]
