# Generated by Django 4.2.9 on 2025-06-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_rename_registration_number_chatsession_reg_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="category",
            field=models.CharField(
                choices=[("degree", "Degree"), ("diploma", "Diploma")],
                default="degree",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(default="00", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
