# Generated by Django 4.2.9 on 2025-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_alter_student_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
