# Generated by Django 4.2.9 on 2025-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_otpstorage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
