# Generated by Django 4.2.9 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_chatsession_last_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("pdf", models.FileField(upload_to="past_papers/")),
            ],
        ),
    ]
