# Generated by Django 4.2.9 on 2025-06-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_pastpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastpaper",
            name="academic_year",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1st Year"),
                    (2, "2nd Year"),
                    (3, "3rd Year"),
                    (4, "4th Year"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pastpaper",
            name="published_year",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pastpaper",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.department"
            ),
        ),
        migrations.AlterField(
            model_name="pastpaper",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
