# Generated by Django 4.2.9 on 2025-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_pastpaper_academic_year_pastpaper_published_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="info",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
