# Generated by Django 4.2.9 on 2025-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_chatsession_data_alter_product_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
