# Generated by Django 4.2.9 on 2025-06-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_announcement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="content",
            new_name="body",
        ),
    ]
